name: Verify

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  schedule:
    - cron: "45 4 * * *"

jobs:
  lint:
    name: Run PHP linter validation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: firehed/lint-php-action@v1

  test:
    name: Test with PHP ${{ matrix.php.version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php:
          - version: "5.6"
          - version: "7.4"
          - version: "8.1"

    steps:
      - uses: actions/checkout@v5
      - name: Setup PHP v${{ matrix.php.version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php.version }}
      - name: Run test suite
        run: php test/index.php

  validate:
    name: Validate
    runs-on: ubuntu-latest

    needs:
      - lint
      - test

    steps:
      - run: true
